(()=>{'use strict';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const base=[['01-brown-charm-crossbody-bag','Brown Charm Crossbody Bag','Accessory'],['02-black-charm-combat-boots','Black Charm Combat Boots','Shoes'],['03-black-pink-piped-track-pants','Black & Pink Track Pants','Bottom'],['04-pink-ambitious-dreamer-long-sleeve','Ambitious Dreamer Top','Top'],['05-white-ribbed-long-sleeve-top','White Ribbed Long-Sleeve','Top'],['06-black-alo-cap','Black Alo Cap','Accessory'],['07-blue-embroidered-dress-sandals','Blue Embroidered Sandals','Shoes'],['08-sage-pink-zip-hoodie','Sage & Pink Zip Hoodie','Outerwear'],['09-navy-cream-nike-retro-sneakers','Nike Retro Sneakers','Shoes'],['10-cream-puff-sleeve-ruffle-blouse','Cream Ruffle Blouse','Top'],['11-cream-contrast-trim-knit-vest','Contrast-Trim Knit Vest','Top'],['12-black-cream-tweed-skort','Black & Cream Tweed Skort','Bottom'],['13-black-nike-boxy-sweatshirt','Nike Boxy Sweatshirt','Top'],['14-black-ribbed-turtleneck','Black Ribbed Turtleneck','Top'],['15-cream-cable-knit-sweater','Cream Cable-Knit Sweater','Top'],['16-navy-paris-cap','Navy Paris Cap','Accessory'],['17-black-cropped-hooded-jacket','Black Cropped Hooded Jacket','Outerwear'],['18-black-heart-puff-sleeve-top','Black Heart Puff-Sleeve Top','Top'],['19-blue-snoopy-denim-tote','Blue Snoopy Denim Tote','Accessory'],['20-cream-knit-tank','Cream Knit Tank','Top'],['21-grey-washed-wide-leg-jeans','Grey Wide-Leg Jeans','Bottom'],['22-cream-distressed-knit-cropped-sweater','Distressed Cropped Sweater','Top'],['23-black-open-knit-wrap-cardigan','Black Open-Knit Cardigan','Outerwear'],['24-grey-washed-denim-skort','Grey Washed Denim Skort','Bottom'],['25-grey-cargo-jeans','Grey Cargo Jeans','Bottom'],['26-beige-chunky-sneakers','Beige Chunky Sneakers','Shoes'],['27-black-hooded-jacket','Black Hooded Jacket','Outerwear'],['28-silver-grey-new-balance-sneakers','New Balance Sneakers','Shoes'],['29-blue-white-pinstripe-drawstring-pants','Pinstripe Drawstring Pants','Bottom'],['30-plaid-bubble-skort','Plaid Bubble Skort','Bottom'],['31-grey-floral-track-pants','Grey Floral Track Pants','Bottom']].map(x=>({id:x[0],name:x[1],category:x[2]}));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const state={items:read('fc_items_v21',read('fc_v3_items',base)),favorites:read('fc_faves',[]),saved:read('fc_saved',[]),wishes:read('fc_v3_wishes',[{name:'Striped rugby top',unlock:9,icon:'👕'},{name:'Navy cardigan',unlock:11,icon:'🧶'},{name:'Silver mini bag',unlock:7,icon:'👜'}]),filter:'All',category:'Top',selected:{Top:null,Bottom:null,Outerwear:null,Shoes:null,Accessory:null},weather:'sunny'};
const item=id=>state.items.find(i=>i.id===id),visual=i=>i?`<img src="${i.image||`assets/${i.id}.png`}" alt="${i.name}">`:'';
function go(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav [data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===id));scrollTo({top:0,behavior:'smooth'})}$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1900)}
const cats=['All','Top','Bottom','Outerwear','Shoes','Accessory'];
function renderCloset(){const q=$('#search').value.toLowerCase();$('#filters').innerHTML=cats.map(c=>`<button class="${state.filter===c?'active':''}" data-filter="${c}">${c}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderCloset()});const found=state.items.filter(i=>(state.filter==='All'||i.category===state.filter)&&i.name.toLowerCase().includes(q));$('#closetGrid').innerHTML=found.map(i=>`<article class="garment" data-category="${i.category}"><button class="favorite ${state.favorites.includes(i.id)?'on':''}" data-fave="${i.id}">♡</button><button class="garment-photo" data-wear="${i.id}">${visual(i)}</button><h3>${i.name}</h3><small>${i.category}</small></article>`).join('');$$('[data-fave]').forEach(b=>b.onclick=()=>{state.favorites=state.favorites.includes(b.dataset.fave)?state.favorites.filter(x=>x!==b.dataset.fave):[...state.favorites,b.dataset.fave];write('fc_faves',state.favorites);renderCloset()});$$('[data-wear]').forEach(b=>b.onclick=()=>{const i=item(b.dataset.wear);state.selected[i.category]=i.id;state.category=i.category;go('style');renderStyle()})}$('#search').oninput=renderCloset;
function renderStyle(){const cs=['Top','Bottom','Outerwear','Shoes','Accessory'];$('#categoryRail').innerHTML=cs.map(c=>`<button class="${state.category===c?'active':''}" data-cat="${c}">${c}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderStyle()});$('#picker').innerHTML=state.items.filter(i=>i.category===state.category).map(i=>`<button class="${state.selected[state.category]===i.id?'selected':''}" data-pick="${i.id}" title="${i.name}">${visual(i)}</button>`).join('');$$('[data-pick]').forEach(b=>b.onclick=()=>{state.selected[state.category]=b.dataset.pick;renderStyle()});Object.entries({Top:'#wearTop',Bottom:'#wearBottom',Outerwear:'#wearOuterwear',Shoes:'#wearShoes',Accessory:'#wearAccessory'}).forEach(([c,s])=>$(s).innerHTML=visual(item(state.selected[c])));const n=Object.values(state.selected).filter(Boolean).length;$('#score').textContent=72+n*5;$('#whyText').textContent=n>=3?'The proportions feel balanced: one clear silhouette, grounded shoes, and a playful focal piece. Swap any category to explore another version.':'Choose at least a top, bottom, and shoes to see a complete head-to-toe look.'}
function random(cat,pref=''){let pool=state.items.filter(i=>i.category===cat),filtered=pool;if(pref==='sporty')filtered=pool.filter(i=>/nike|track|cargo|sneaker|hood/i.test(i.name));if(pref==='preppy')filtered=pool.filter(i=>/cream|plaid|tweed|knit|ribbed/i.test(i.name));pool=filtered.length?filtered:pool;return pool[Math.floor(Math.random()*pool.length)]?.id||null}
function shuffle(pref=''){['Top','Bottom','Shoes'].forEach(c=>state.selected[c]=random(c,pref));state.selected.Outerwear=Math.random()>.45?random('Outerwear',pref):null;state.selected.Accessory=Math.random()>.5?random('Accessory',pref):null;renderStyle();toast('A new full look appeared ✦')}$('#shuffle').onclick=()=>shuffle();$$('[data-refine]').forEach(b=>b.onclick=()=>{shuffle(b.dataset.refine);$('#lookTitle').textContent=`More ${b.dataset.refine}`});
$('#saveLook').onclick=()=>{state.saved.push({name:$('#lookTitle').textContent,selected:{...state.selected},date:Date.now()});write('fc_saved',state.saved);renderSaved();toast('Look saved ♡')};
const trends=[{name:'Seoul Sporty Layers',desc:'A fitted dark top, wide denim, retro runners, and a cap.',owned:4,need:'Striped rugby top',art:'⚡',color:'#ff9fc1',ids:['13-black-nike-boxy-sweatshirt','21-grey-washed-wide-leg-jeans','09-navy-cream-nike-retro-sneakers','16-navy-paris-cap']},{name:'Tokyo Soft Preppy',desc:'Cream knit, plaid mini, neutral sneakers, optional dark layer.',owned:3,need:'Navy cardigan',art:'✦',color:'#d8c7ff',ids:['15-cream-cable-knit-sweater','30-plaid-bubble-skort','26-beige-chunky-sneakers']},{name:'Cool-Girl Cargo',desc:'Black base, washed cargos, chunky footwear, playful bag.',owned:4,need:'Silver hair clips',art:'★',color:'#9ce1ca',ids:['14-black-ribbed-turtleneck','25-grey-cargo-jeans','02-black-charm-combat-boots','01-brown-charm-crossbody-bag']},{name:'Sweet Street Remix',desc:'Romantic blouse balanced with relaxed denim and sporty shoes.',owned:3,need:'Cherry red cardigan',art:'♡',color:'#ffd98a',ids:['10-cream-puff-sleeve-ruffle-blouse','21-grey-washed-wide-leg-jeans','28-silver-grey-new-balance-sneakers']}];
function renderTrends(){$('#trendGrid').innerHTML=trends.map((t,n)=>`<article class="trend"><div class="trend-art" style="background:${t.color}" data-label="INSPO · CURATED SAMPLE">${t.art}</div><div class="trend-body"><h2>${t.name}</h2><p>${t.desc}</p><span class="owned-badge">✓ ${t.owned}/${t.owned+1} pieces matched</span><small>Missing idea: ${t.need}</small><div class="trend-actions"><button class="primary" data-recreate="${n}">Recreate it</button><button class="secondary" data-wish="${t.need}">＋ Wishlist</button></div></div></article>`).join('');$$('[data-recreate]').forEach(b=>b.onclick=()=>{const t=trends[+b.dataset.recreate];Object.keys(state.selected).forEach(c=>state.selected[c]=null);t.ids.map(item).filter(Boolean).forEach(i=>state.selected[i.category]=i.id);$('#lookTitle').textContent=t.name;go('style');renderStyle();toast('Recreated with Fiona’s closet')});$$('[data-wish]').forEach(b=>b.onclick=()=>{state.wishes.push({name:b.dataset.wish,unlock:8,icon:'✦'});write('fc_v3_wishes',state.wishes);renderWishes();toast('Added to Dream Closet')})}
const weatherMap={sunny:['☀️','Mild & sunny · 68°F','preppy'],cool:['☁️','Cool & cloudy · layers please','cozy'],rain:['☂️','Rainy · practical layers','sporty'],hot:['🌤️','Warm day · keep it light','']};function renderWeather(){const w=weatherMap[state.weather];$('#weatherIcon').textContent=w[0];$('#weatherSummary').textContent=w[1];$('#weatherPill').textContent=`${w[0]} ${state.weather==='hot'?'82':'68'}°F`;$$('[data-weather]').forEach(b=>b.classList.toggle('active',b.dataset.weather===state.weather))}$$('[data-weather]').forEach(b=>b.onclick=()=>{state.weather=b.dataset.weather;renderWeather()});$('#weatherLook').onclick=()=>{shuffle(weatherMap[state.weather][2]);if(['cool','rain'].includes(state.weather))state.selected.Outerwear=random('Outerwear');go('style');renderStyle();$('#lookTitle').textContent='Weather-ready look'};
$('#buildPack').onclick=()=>{const days=Math.max(1,Math.min(14,+$('#tripDays').value||3)),tops=state.items.filter(i=>i.category==='Top').slice(0,Math.min(days+1,5)),bottoms=state.items.filter(i=>i.category==='Bottom').slice(0,Math.min(Math.ceil(days/2)+1,4)),shoes=state.items.filter(i=>i.category==='Shoes').slice(0,2),layers=$('#tripWeather').value==='Warm'?[]:state.items.filter(i=>i.category==='Outerwear').slice(0,1),all=[...tops,...bottoms,...shoes,...layers];$('#packResult').innerHTML=`<h2>${$('#tripVibe').value}: ${days}-day capsule</h2><p>${all.length} pieces · approximately ${days*2} mixable outfits</p><div class="pack-grid">${all.map(i=>`<div class="pack-item">${visual(i)}<b>${i.name}</b></div>`).join('')}</div>`};
function renderWishes(){$('#wishGrid').innerHTML=state.wishes.map((w,n)=>`<article class="wish-card"><span>${w.icon}</span><b>${w.name}</b><p>Could unlock about ${w.unlock} looks using Fiona's closet.</p><button class="secondary" data-remove-wish="${n}">Remove</button></article>`).join('');$$('[data-remove-wish]').forEach(b=>b.onclick=()=>{state.wishes.splice(+b.dataset.removeWish,1);write('fc_v3_wishes',state.wishes);renderWishes()})}$('#addWish').onclick=()=>{const name=prompt('What garment idea should we save?');if(name){state.wishes.push({name,unlock:5+Math.ceil(Math.random()*8),icon:'✦'});write('fc_v3_wishes',state.wishes);renderWishes()}};
function renderSaved(){$('#savedGrid').innerHTML=state.saved.length?state.saved.map(l=>`<article class="saved-look"><h3>${l.name||'Saved look'}</h3>${['Top','Bottom','Shoes'].map(c=>visual(item(l.selected?.[c]||l[c]))).join('')}</article>`).join(''):'<p>No saved looks yet. Make one in the Magic Mirror!</p>'}
const dlg=$('#itemDialog'),form=$('#itemForm'),file=form.elements.photo;$('#addItem').onclick=()=>dlg.showModal();$('.close').onclick=()=>dlg.close();file.onchange=()=>{const f=file.files[0];if(!f)return;$('#preview').src=URL.createObjectURL(f);$('#preview').style.display='block'};form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),f=fd.get('photo'),reader=new FileReader();reader.onload=()=>{state.items.push({id:`custom-${Date.now()}`,name:fd.get('name'),category:fd.get('category'),image:reader.result});write('fc_v3_items',state.items);write('fc_items_v21',state.items);dlg.close();form.reset();$('#preview').style.display='none';renderCloset();toast('New piece saved on this device')};reader.readAsDataURL(f)};
// V3.5 Avatar Studio uses curated, device-local presets only.
const avatarDefaults={hair:'waves',hairColor:'brunette',makeup:'fresh',vibe:'sweet'};
const avatarState={...avatarDefaults,...read('fc_v35_avatar',{})};
const avatarImage=document.createElement('img');avatarImage.className='avatar-base';avatarImage.src='assets/fiona-avatar-approved.png';avatarImage.alt="Fiona wearing a white blouse, black pleated skirt, and sneakers";$('#avatar').prepend(avatarImage);$('#avatarAssetNote').remove();
function renderAvatar(){const avatar=$('#avatar');Object.entries(avatarState).forEach(([key,value])=>avatar.setAttribute(`data-${key.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}`,value));$$('[data-avatar-key]').forEach(button=>{const active=avatarState[button.dataset.avatarKey]===button.dataset.avatarValue;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});write('fc_v35_avatar',avatarState)}
$$('[data-avatar-key]').forEach(button=>button.onclick=()=>{avatarState[button.dataset.avatarKey]=button.dataset.avatarValue;renderAvatar();toast('Avatar updated ✦')});
$('#resetAvatar').onclick=()=>{Object.assign(avatarState,avatarDefaults);renderAvatar();toast('Avatar reset')};
const baseRenderStyle=renderStyle;renderStyle=()=>{baseRenderStyle();const accessory=item(state.selected.Accessory),slot=$('#wearAccessory'),bottom=item(state.selected.Bottom);slot.classList.toggle('is-hat',!!accessory&&/cap|hat/i.test(accessory.name));slot.classList.toggle('is-bag',!!accessory&&/bag|tote|crossbody/i.test(accessory.name));$('#wearBottom').classList.toggle('is-short',!!bottom&&/skort|skirt/i.test(bottom.name))};
// V4 product modules: centralized fits, visible hair, reconstruction, and travel outfits.
const FIT_CONFIG={Top:{x:0,y:126,w:205,h:180,z:4},Outerwear:{x:0,y:116,w:224,h:215,z:6},Bottom:{x:0,y:215,w:202,h:220,z:4},Short:{x:0,y:224,w:184,h:154,z:4},Shoes:{x:0,y:410,w:174,h:70,z:7},Hat:{x:0,y:22,w:132,h:100,z:8},Bag:{x:104,y:172,w:120,h:180,z:8},Accessory:{x:98,y:145,w:104,h:150,z:8}};
function fitKey(i){if(!i)return'';if(i.category==='Bottom'&&/skort|skirt/i.test(i.name))return'Short';if(i.category==='Accessory'&&/cap|hat/i.test(i.name))return'Hat';if(i.category==='Accessory'&&/bag|tote|crossbody/i.test(i.name))return'Bag';return i.category}
function applyFit(category,selector){const i=item(state.selected[category]),f=FIT_CONFIG[fitKey(i)]||FIT_CONFIG[category],el=$(selector);Object.entries(f||{}).forEach(([k,v])=>el.style.setProperty(`--fit-${k}`,`${v}${['z'].includes(k)?'':'px'}`));el.dataset.fit=fitKey(i)}
const v4RenderStyle=renderStyle;renderStyle=()=>{v4RenderStyle();Object.entries({Top:'#wearTop',Bottom:'#wearBottom',Outerwear:'#wearOuterwear',Shoes:'#wearShoes',Accessory:'#wearAccessory'}).forEach(([c,s])=>applyFit(c,s));$('#avatar').classList.add('garment-change');clearTimeout(renderStyle.t);renderStyle.t=setTimeout(()=>$('#avatar').classList.remove('garment-change'),260)};
const hairLayer=document.createElement('i');hairLayer.className='hair-visual';hairLayer.setAttribute('aria-hidden','true');$('#avatar').prepend(hairLayer);['makeup','vibe'].forEach(k=>$(`[data-avatar-key="${k}"]`)?.closest('fieldset')?.remove());

let activeRecreate=null;
function closest(category,exclude=[]){return state.items.find(i=>i.category===category&&!exclude.includes(i.id))}
function showRecreate(n){const t=trends[n],owned=t.ids.map(item).filter(Boolean),categories=['Top','Bottom','Shoes','Outerwear','Accessory'],choices={};owned.forEach(i=>choices[i.category]=i.id);activeRecreate={trend:n,choices};const matched=categories.filter(c=>choices[c]).length,percent=Math.round(matched/categories.length*100);$('#recreatePanel').innerHTML=`<div class="match-head"><span class="match-ring">${percent}%</span><div><span class="eyebrow">Closet match</span><h2>${t.name}</h2></div></div><div class="match-list">${categories.map(c=>{const chosen=item(choices[c]),alt=closest(c,chosen?[chosen.id]:[]);return`<article class="match-row"><span class="status ${chosen?'owned':'missing'}">${chosen?'✓ Owned':'＋ Missing'}</span><b>${c}</b><div class="match-pieces">${chosen?visual(chosen):'<span class="missing-tile">?</span>'}<span><strong>${chosen?.name||t.need}</strong><small>${chosen?'Exact closet match':alt?`Closest: ${alt.name}`:'No owned alternative'}</small></span></div>${alt?`<button class="secondary" data-replace-cat="${c}" data-replace-id="${alt.id}">Use alternative</button>`:''}</article>`}).join('')}</div><div class="recreate-actions"><button class="primary" id="openRecreated">Open in Magic Mirror</button><button class="secondary" id="wishMissing">Send missing to Wishlist</button></div>`;$$('[data-replace-cat]').forEach(b=>b.onclick=()=>{activeRecreate.choices[b.dataset.replaceCat]=b.dataset.replaceId;showRecreateWithChoices(n,activeRecreate.choices)});$('#openRecreated').onclick=()=>{Object.keys(state.selected).forEach(c=>state.selected[c]=activeRecreate.choices[c]||null);$('#lookTitle').textContent=t.name;go('style');renderStyle()};$('#wishMissing').onclick=()=>{categories.filter(c=>!activeRecreate.choices[c]).forEach(()=>state.wishes.push({name:t.need,unlock:8,icon:'✦'}));write('fc_v3_wishes',state.wishes);renderWishes();toast('Missing pieces saved to Wishlist')}}
function showRecreateWithChoices(n,choices){const saved={...choices};showRecreate(n);activeRecreate.choices=saved;Object.assign(activeRecreate.choices,saved);$('#recreatePanel').querySelectorAll('.match-row').forEach(row=>{const c=row.querySelector('b')?.textContent,i=item(saved[c]);if(i){row.querySelector('.match-pieces').innerHTML=`${visual(i)}<span><strong>${i.name}</strong><small>Chosen alternative</small></span>`}})}
renderTrends=()=>{$('#trendGrid').innerHTML=trends.map((t,n)=>`<article class="trend"><div class="trend-art" style="background:${t.color}" data-label="CURATED INSPIRATION">${t.art}</div><div class="trend-body"><h2>${t.name}</h2><p>${t.desc}</p><button class="primary" data-breakdown="${n}">Recreate this look</button></div></article>`).join('');$$('[data-breakdown]').forEach(b=>b.onclick=()=>showRecreate(+b.dataset.breakdown))};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!activeRecreate)return;if(b.id==='openRecreated'){Object.keys(state.selected).forEach(c=>state.selected[c]=activeRecreate.choices[c]||null);$('#lookTitle').textContent=trends[activeRecreate.trend].name;go('style');renderStyle()}if(b.id==='wishMissing'){const t=trends[activeRecreate.trend];['Top','Bottom','Shoes','Outerwear','Accessory'].filter(c=>!activeRecreate.choices[c]).forEach(()=>state.wishes.push({name:t.need,unlock:8,icon:'✦'}));write('fc_v3_wishes',state.wishes);renderWishes();toast('Missing pieces saved to Wishlist')}});

$('#buildPack').onclick=()=>{const days=Math.max(1,Math.min(14,+$('#tripDays').value||3)),destination=$('#tripDestination').value||'Trip',vibe=$('#tripVibe').value,activity=$('#tripActivities').value,weather=$('#tripWeather').value,wordMap={'City weekend':/black|cargo|denim|sneaker/i,'Beach break':/tank|sandal|cream|blue/i,'School trip':/hood|nike|track|sneaker/i,'Family holiday':/cream|knit|plaid|bag/i},re=wordMap[vibe],rank=xs=>[...xs].sort((a,b)=>Number(re.test(b.name))-Number(re.test(a.name))),take=(c,n)=>rank(state.items.filter(i=>i.category===c)).slice(0,n),tops=take('Top',Math.min(days+1,4)),bottoms=take('Bottom',Math.min(Math.ceil(days/2)+1,3)),shoes=take('Shoes',2),layers=weather==='Warm'?[]:take('Outerwear',weather==='Rainy'||weather==='Cool'?2:1),extras=take('Accessory',1),capsule=[...tops,...bottoms,...shoes,...layers,...extras],outfits=Array.from({length:days},(_,d)=>[tops[d%tops.length],bottoms[(d*2)%bottoms.length],shoes[d%shoes.length],layers.length?layers[d%layers.length]:null].filter(Boolean));$('#packResult').innerHTML=`<div class="pack-summary"><div><span class="eyebrow">${destination} · ${weather}</span><h2>${days}-day ${vibe}</h2><p>${activity} · ${capsule.length} owned pieces</p></div><span class="pack-count">${outfits.length}<small>outfits</small></span></div><h3>Visual packing checklist</h3><div class="pack-grid">${capsule.map(i=>`<label class="pack-item"><input type="checkbox">${visual(i)}<b>${i.name}</b></label>`).join('')}</div><h3>Day-by-day outfits</h3><div class="day-grid">${outfits.map((look,d)=>`<article class="day-card"><span>DAY ${d+1}</span><div>${look.map(visual).join('')}</div><b>${look.map(i=>i.name).join(' + ')}</b></article>`).join('')}</div><p class="missing-note">${weather==='Rainy'&&!state.items.some(i=>/rain|waterproof/i.test(i.name))?'Missing: a waterproof layer would complete this capsule.':'Everything in this capsule comes from Fiona’s closet.'}</p>`};

renderCloset();renderStyle();renderTrends();renderWeather();renderWishes();renderSaved();renderAvatar();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
})();
