(() => {
  const $ = (s, p=document) => p.querySelector(s), $$ = (s,p=document) => [...p.querySelectorAll(s)];
  const colors=['#ff76a8','#8edfc4','#9271e6','#ffd05f','#72cbe7','#ef91da'];
  const fallbackItems=[
    {id:'top-pink',name:'Pink Pop Tee',category:'Top',color:'#ff79ac',icon:'♡'},
    {id:'top-jersey',name:'Graphic 96 Jersey',category:'Top',color:'#33243e',icon:'96'},
    {id:'top-stripe',name:'Striped Ruffle Shirt',category:'Top',color:'#e8a7b9',icon:'✦'},
    {id:'bottom-cargo',name:'Black Cargo Pants',category:'Bottom',color:'#4b4653',icon:'✦'},
    {id:'bottom-plaid',name:'Plaid Mini Skirt',category:'Bottom',color:'#9b6f86',icon:'▦'},
    {id:'bottom-gray',name:'Soft Gray Skirt',category:'Bottom',color:'#a9a7b0',icon:'♡'},
    {id:'outer-denim',name:'Cropped Denim Jacket',category:'Outerwear',color:'#72b7dd',icon:'★'},
    {id:'shoe-sneaker',name:'Retro Sneakers',category:'Shoes',color:'#e9e6da',icon:'⚡'},
    {id:'acc-bag',name:'Mini Shoulder Bag',category:'Accessory',color:'#f6c75e',icon:'☻'}
  ];
  const worlds=[['K-Sporty Pop','Jerseys, wide legs & shiny details','⚡','#ff9abd'],['Soft Academia','Plaid, cardigans & clever layers','✎','#d8c7ff'],['Color Splash','Unexpected brights that love each other','✦','#ffda6b'],['Skater Weekend','Relaxed shapes with graphic energy','★','#94dfca'],['Sweet Vintage','Tiny florals, denim & playful accessories','♡','#f4b1d6'],['Clean Remix','Simple favorites styled a new way','↻','#9ddcf0']];
  const wishes=[['Cream cardigan','🧶',11,'#fff0c6'],['Cherry red sneakers','👟',8,'#ffd5df'],['Silver mini bag','👜',7,'#e2ddf5'],['Striped rugby top','👕',9,'#d8f4e8'],['Denim maxi skirt','👗',6,'#d7eafa'],['Star hair clips','★',5,'#fff0a8']];
  const moods=['🎀 Cute','⚡ Sporty','✦ Bold','☁ Cozy','★ School','♡ Surprise me'];
  const state={items:load('fc_items',fallbackItems),saved:load('fc_saved',[]),favorites:load('fc_faves',[]),filter:'All',dock:'Top',mood:'🎀 Cute',selected:{Top:null,Bottom:null,Shoes:null}};
  function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}} function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
  function route(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===name&&b.closest('.bottom-nav')));window.scrollTo({top:0,behavior:'smooth'});$('#app').focus({preventScroll:true});}
  $$('[data-route]').forEach(b=>b.addEventListener('click',()=>route(b.dataset.route)));
  const cats=['All','Top','Bottom','Outerwear','Shoes','Accessory'];
  function imageCandidates(item){return item.image?[item.image]:[`assets/${item.id}.png`,`assets/${item.id}.jpg`,`assets/${item.id}.jpeg`,`assets/${item.id}.webp`];}
  function itemVisual(item, cls=''){const imgs=imageCandidates(item);return `<img class="${cls}" src="${imgs[0]}" alt="${item.name}" data-fallbacks='${JSON.stringify(imgs.slice(1))}'><span class="garment-placeholder" style="background:${item.color||colors[0]}">${item.icon||'✦'}</span>`}
  document.addEventListener('load',e=>{if(e.target.tagName==='IMG'&&e.target.nextElementSibling?.classList.contains('garment-placeholder'))e.target.nextElementSibling.style.display='none'},true);
  document.addEventListener('error',e=>{if(e.target.tagName!=='IMG')return;let a=[];try{a=JSON.parse(e.target.dataset.fallbacks||'[]')}catch{}if(a.length){e.target.src=a.shift();e.target.dataset.fallbacks=JSON.stringify(a)}else e.target.style.display='none'},true);
  function renderFilters(){ $('#closetFilters').innerHTML=cats.map(c=>`<button class="${state.filter===c?'active':''}" data-filter="${c}">${c}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderFilters();renderCloset()}) }
  function renderCloset(){const q=$('#closetSearch').value.toLowerCase(), filtered=state.items.filter(i=>(state.filter==='All'||i.category===state.filter)&&i.name.toLowerCase().includes(q));$('#garmentGrid').innerHTML=filtered.map((i,n)=>`<article class="garment-card" data-id="${i.id}"><button class="favorite ${state.favorites.includes(i.id)?'on':''}" aria-label="Favorite">♡</button><button class="garment-photo" data-wear="${i.id}" aria-label="Style ${i.name}">${itemVisual(i)}</button><h3>${i.name}</h3><small>${i.category} · ${['Everyday','Playful','Easy layer'][n%3]}</small></article>`).join('')||'<p>No pieces found. Try another search.</p>';$('#itemCount').textContent=state.items.length;$('#comboCount').textContent=Math.max(6,state.items.filter(i=>i.category==='Top').length*state.items.filter(i=>i.category==='Bottom').length*3);$$('.favorite').forEach(b=>b.onclick=()=>{const id=b.closest('[data-id]').dataset.id;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save('fc_faves',state.favorites);renderCloset()});$$('[data-wear]').forEach(b=>b.onclick=()=>{const i=state.items.find(x=>x.id===b.dataset.wear);if(['Top','Bottom','Shoes'].includes(i.category))state.selected[i.category]=i.id;route('style');state.dock=i.category;renderStyle();toast(`${i.name} added to your look`)})}
  $('#closetSearch').oninput=renderCloset;
  function renderMoods(){ $('#moodRow').innerHTML=moods.map(m=>`<button class="${m===state.mood?'active':''}" data-mood="${m}">${m}</button>`).join('');$$('[data-mood]').forEach(b=>b.onclick=()=>{state.mood=b.dataset.mood;renderMoods();$('#lookName').textContent=b.textContent.replace(/[^a-z ]/gi,'').trim()+' Mix';updateScore()})}
  function renderStyle(){const tabs=['Top','Bottom','Shoes'];$('#dockTabs').innerHTML=tabs.map(c=>`<button class="${c===state.dock?'active':''}" data-dock="${c}">${c}</button>`).join('');$$('[data-dock]').forEach(b=>b.onclick=()=>{state.dock=b.dataset.dock;renderStyle()});const items=state.items.filter(i=>i.category===state.dock);$('#dockItems').innerHTML=items.map(i=>`<button class="dock-item ${state.selected[state.dock]===i.id?'selected':''}" data-pick="${i.id}">${itemVisual(i)}<span>${i.name}</span></button>`).join('');$$('[data-pick]').forEach(b=>b.onclick=()=>{state.selected[state.dock]=b.dataset.pick;renderStyle();updateScore()});[['Top','#topSlot'],['Bottom','#bottomSlot'],['Shoes','#shoeSlot']].forEach(([cat,sel])=>{const item=state.items.find(i=>i.id===state.selected[cat]);$(sel).innerHTML=item?itemVisual(item):`<span>Choose ${cat.toLowerCase()}</span>`});updateScore()}
  function updateScore(){const count=Object.values(state.selected).filter(Boolean).length,score=74+count*6+Math.floor(Math.random()*4);$('#styleScore').textContent=score;$('#matchValue').textContent=count===3?'100%':`${55+count*15}%`;$('#matchBar').style.width=$('#matchValue').textContent;$('#styleNote').textContent=count===3?'This look has a strong silhouette and a fun color story. It is ready to wear!':'Choose another piece and watch your outfit story come together.'}
  function shuffle(){['Top','Bottom','Shoes'].forEach(cat=>{const pool=state.items.filter(i=>i.category===cat);state.selected[cat]=pool[Math.floor(Math.random()*pool.length)]?.id||null});renderStyle();confetti();toast('A fresh outfit appeared!')}
  $('#shuffleLook').onclick=shuffle;$('#surpriseMe').onclick=()=>{route('style');shuffle()};$('#saveLook').onclick=()=>{state.saved.push({...state.selected,name:$('#lookName').textContent,date:Date.now()});save('fc_saved',state.saved);$('#savedStat').textContent=state.saved.length;confetti();toast('Look saved to your style story ♡')};$('#renameLook').onclick=()=>{const n=prompt('Name this look',$('#lookName').textContent);if(n)$('#lookName').textContent=n};
  function renderDiscover(){const tabs=['For You','Trending Now','Use My Closet','Try Something New'];$('#discoverTabs').innerHTML=tabs.map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join('');$$('#discoverTabs button').forEach(b=>b.onclick=()=>{$$('#discoverTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`${b.textContent} inspiration loaded`)});$('#worldGrid').innerHTML=worlds.map(w=>`<button class="world-card" style="background:${w[3]}" data-world="${w[0]}"><strong>${w[0]}</strong><small>${w[1]}</small><span class="world-icon">${w[2]}</span></button>`).join('');$$('[data-world]').forEach(b=>b.onclick=()=>{state.mood='✦ Bold';route('style');shuffle();$('#lookName').textContent=b.dataset.world})}
  function renderWishlist(){ $('#wishGrid').innerHTML=wishes.map((w,i)=>`<article class="wish-card"><div class="wish-visual" style="background:${w[3]}">${w[1]}</div><span class="unlock">UNLOCKS ${w[2]} LOOKS</span><h3>${w[0]}</h3><small>Works with ${Math.min(state.items.length,5+i)} pieces you own</small><div class="wish-actions"><button class="secondary wish-remove">Remove</button><button class="primary wish-style">Try it</button></div></article>`).join('');$$('.wish-remove').forEach(b=>b.onclick=()=>{b.closest('.wish-card').remove();toast('Removed from wishlist')});$$('.wish-style').forEach(b=>b.onclick=()=>{route('style');shuffle()})}
  $('#refreshTrends').onclick=()=>{worlds.sort(()=>Math.random()-.5);renderDiscover();toast('Fresh style worlds loaded ✦')};$('#tryTrend').onclick=()=>{route('style');shuffle();$('#lookName').textContent='Sporty Layers'};$('#addWish').onclick=()=>{const n=prompt('What garment are you dreaming of?');if(n){wishes.unshift([n,'✦',Math.ceil(Math.random()*9)+3,colors[Math.floor(Math.random()*colors.length)]]);renderWishlist();toast('Idea added to your dream closet')}};
  const dlg=$('#itemDialog'),form=$('#itemForm');$('#addItem').onclick=()=>dlg.showModal();form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),file=fd.get('photo');const finish=image=>{state.items.push({id:'custom-'+Date.now(),name:fd.get('name'),category:fd.get('category'),color:colors[state.items.length%colors.length],icon:'✦',image});save('fc_items',state.items);dlg.close();form.reset();state.filter='All';renderFilters();renderCloset();toast('New piece added!')};if(file&&file.size){const r=new FileReader();r.onload=()=>finish(r.result);r.readAsDataURL(file)}else finish(null)});
  $('#soundToggle').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♫'?'♪̸':'♫';toast(e.currentTarget.textContent==='♫'?'Sounds on':'Sounds off')};
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
  function confetti(){const wrap=$('.confetti');for(let i=0;i<28;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'vw';p.style.background=colors[i%colors.length];p.style.animationDelay=Math.random()*.35+'s';p.style.transform=`rotate(${Math.random()*180}deg)`;wrap.append(p);setTimeout(()=>p.remove(),2000)}}
  renderFilters();renderCloset();renderMoods();renderStyle();renderDiscover();renderWishlist();$('#savedStat').textContent=state.saved.length;
})();
