const pages={
home:`<section class="hero"><h2>What are we wearing today?</h2><p>Mix your closet, discover a vibe, or let the stylist surprise you.</p><button class="btn" onclick="go('style')">Style me ✦</button><div class="art">🧥</div></section><section class="section"><h3>Trending now</h3><div class="cards"><div class="card"><div class="pic">🎧</div><span class="tag">TRENDING</span><h4>Seoul Sporty</h4><div class="muted">You own 3/4 pieces</div></div><div class="card"><div class="pic">🪩</div><span class="tag">FOR YOU</span><h4>Soft Grunge</h4><div class="score">89% match</div></div><div class="card"><div class="pic">⭐</div><span class="tag">NEW</span><h4>Retro Campus</h4><div class="muted">6 looks unlocked</div></div></div></section><section class="section"><h3>Play with your closet</h3><div class="grid"><button class="tile pink" onclick="go('closet')">My Closet<br><br>👚</button><button class="tile purple" onclick="go('style')">Outfit Lab<br><br>✨</button><button class="tile blue" onclick="go('discover')">Discover<br><br>🔎</button><button class="tile yellow" onclick="go('wishlist')">Wishlist<br><br>🛍️</button></div></section>`,
closet:`<h2>My Closet ♡</h2><div class="pills"><button class="pill">All</button><button class="pill">Tops</button><button class="pill">Bottoms</button><button class="pill">Layers</button><button class="pill">Shoes</button></div><div class="grid"><div class="card"><div class="pic">👕</div><h4>Tops</h4></div><div class="card"><div class="pic">👖</div><h4>Bottoms</h4></div><div class="card"><div class="pic">🧥</div><h4>Layers</h4></div><div class="card"><div class="pic">👟</div><h4>Shoes</h4></div></div><button class="btn section">＋ Add garment</button>`,
style:`<h2>Style Me ✦</h2><p class="muted">Choose a mood and build a look from your closet.</p><div class="pills"><button class="pill">School</button><button class="pill">Weekend</button><button class="pill">Party</button><button class="pill">Comfy</button></div><div class="look"><div class="lookpic">👚<br>👖</div><h3 id="lookname">Seoul Sporty</h3><span class="score">92% closet match</span><p class="muted">Everything in this look is already in your closet.</p><button class="btn" onclick="shuffleLook()">Shuffle look ↻</button></div>`,
discover:`<h2>Discover ☻</h2><p>Fashion inspiration translated into looks you can actually wear.</p><div class="cards"><div class="card"><div class="pic">🧢</div><span class="tag">HOT NOW</span><h4>Sporty Korean</h4><div class="score">87% match</div></div><div class="card"><div class="pic">🦋</div><span class="tag">AESTHETIC</span><h4>Y2K Lite</h4><div class="score">74% match</div></div></div><section class="section"><h3>Complete the look</h3><div class="look"><b>One new piece = 8 new outfits</b><p class="muted">A zip jacket would work with your cargos, wide-leg pants and graphic tops.</p><button class="btn" onclick="go('wishlist')">Add idea to wishlist</button></div></section>`,
wishlist:`<h2>Wishlist ☆</h2><p class="muted">Ideas ranked by how much they expand your closet.</p><div class="look"><h3>Zip jacket</h3><span class="score">+8 outfit combinations</span><p>High match with your existing bottoms.</p></div><br><div class="look"><h3>Retro sneakers</h3><span class="score">+6 outfit combinations</span><p>Works with sporty and campus looks.</p></div><button class="btn section">＋ Add an idea</button>`};
function go(v){document.getElementById('view').innerHTML=pages[v];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v));localStorage.setItem('fcview',v)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.v));
function shuffleLook(){let a=['Seoul Sporty','Retro Campus','Soft Grunge','Weekend Layered'];document.getElementById('lookname').textContent=a[Math.floor(Math.random()*a.length)]}
go(localStorage.getItem('fcview')||'home');